language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.1.0
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-google_apis-21

  licenses:
    - '.+'

script:
  - ./gradlew connectedCheck
